### ISSUE TITLE
Not able to install on python 3.8.3 windows 10

### ISSUE THREAD

**Issue by rahulmr** [sjev/trading-with-python#10]
Could you please check why this lib is not getting installed on windows 10 with python 3.8.3?

Thanks.
`python -m pip install tradingWithPython`  

```
  Using cached tradingWithPython-3.1.3.0.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Apps\Scoop\apps\python\current\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iwx\\AppData\\Local\\Temp\\pip-install-o90uc5v7\\tradingWithPython\\setup.py'"'"'; __file__='"'"'C:\\Users\\iwx\\AppData\\Local\\Temp\\pip-install-o90uc5v7\\tradingWithPython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\iwx\AppData\Local\Temp\pip-pip-egg-info-izk03q8b'
         cwd: C:\Users\iwx\AppData\Local\Temp\pip-install-o90uc5v7\tradingWithPython\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\iwx\AppData\Local\Temp\pip-install-o90uc5v7\tradingWithPython\setup.py", line 3, in <module>
        import tradingWithPython as twp
      File "C:\Users\iwx\AppData\Local\Temp\pip-install-o90uc5v7\tradingWithPython\tradingWithPython\__init__.py", line 11, in <module>
        from .lib import cboe
      File "C:\Users\iwx\AppData\Local\Temp\pip-install-o90uc5v7\tradingWithPython\tradingWithPython\lib\cboe.py", line 249, in <module>
        vixExpirations = _loadExpirationDates()
      File "C:\Users\iwx\AppData\Local\Temp\pip-install-o90uc5v7\tradingWithPython\tradingWithPython\lib\cboe.py", line 22, in _loadExpirationDates
        with open(fName,'r') as fid:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\iwx\\AppData\\Local\\Temp\\pip-install-o90uc5v7\\tradingWithPython\\tradingWithPython\\lib\\data\\vix_expiration.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rahulmr** [comment]
I was able to install using source code. May be you can create a new release. Getting some error/warning in case of print statement.

**Comment by 51bitquant** [comment]
He didn't provide a setup.py, so you can't install with the pip.

**Comment by hlar65** [comment]
I have the same issues - can not install the module tradingWithPython

Using cached tradingWithPython-3.1.3.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-i8hson5r\tradingwithpython_7b87b302506d40e1962c32f5d9e07a45\setup.py", line 3, in <module>
          import tradingWithPython as twp
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-i8hson5r\tradingwithpython_7b87b302506d40e1962c32f5d9e07a45\tradingWithPython\__init__.py", line 7, in <module>
          from .lib import yahooFinance
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-i8hson5r\tradingwithpython_7b87b302506d40e1962c32f5d9e07a45\tradingWithPython\lib\yahooFinance.py", line 318, in <module>
          _token = loadToken() # get token from disk or yahoo
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-i8hson5r\tradingwithpython_7b87b302506d40e1962c32f5d9e07a45\tradingWithPython\lib\yahooFinance.py", line 275, in loadToken
          age = (dt.datetime.now()- dt.datetime.strptime(  data['timestamp'], dateTimeFormat) ).days
      KeyError: 'timestamp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sjev** [comment]
stale

**Comment by 51bitquant** [comment]
Hi thanks for using the codes. for compatiblity, please use python 3.10 or above, use the latest python please. thanks.
